/**
 * export.js — 報告匯出功能
 * Lung Cancer Analysis System
 *
 * 提供 PDF 與純文字格式的報告匯出，觸發瀏覽器下載。
 */

/**
 * 觸發瀏覽器下載 Blob 資料
 * @param {Blob} blob - 要下載的資料
 * @param {string} filename - 下載檔案名稱
 */
function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.style.display = 'none';

  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);

  // 釋放 Blob URL（延遲以確保下載已開始）
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * 產生預設檔案名稱（含時間戳記）
 * @param {string} prefix - 檔案名稱前綴
 * @param {string} extension - 副檔名（不含點）
 * @returns {string}
 */
function generateFilename(prefix, extension) {
  const now = new Date();
  const timestamp = now
    .toISOString()
    .replace(/[:.]/g, '-')
    .replace('T', '_')
    .slice(0, 19);
  return `${prefix}_${timestamp}.${extension}`;
}

/**
 * 匯出報告為 PDF（呼叫後端 /api/export-report）
 * @param {object} report - StructuredReport 物件
 * @param {string} report.findings - FINDINGS 段落
 * @param {string} report.impression - IMPRESSION 段落
 * @param {string} report.recommendation - RECOMMENDATION 段落
 * @param {string} [report.generated_at] - 產生時間
 * @returns {Promise<void>}
 * @throws {ApiError} 若後端呼叫失敗
 */
async function exportAsPDF(report) {
  const { LungCancerAPI, LungCancerUI } = window;

  if (!LungCancerAPI) {
    throw new Error('API 模組未載入');
  }

  try {
    const blob = await LungCancerAPI.exportReport(report, 'pdf');
    const filename = generateFilename('lung_cancer_report', 'pdf');
    triggerDownload(blob, filename);

    if (LungCancerUI) {
      LungCancerUI.showSuccessToast('PDF 報告已開始下載');
    }
  } catch (error) {
    if (LungCancerUI) {
      LungCancerUI.showErrorToast(
        'PDF 匯出失敗',
        error.detail || error.message
      );
    }
    throw error;
  }
}

/**
 * 匯出報告為純文字（在瀏覽器端直接產生，不需後端）
 * @param {object} report - StructuredReport 物件
 * @param {string} report.findings - FINDINGS 段落
 * @param {string} report.impression - IMPRESSION 段落
 * @param {string} report.recommendation - RECOMMENDATION 段落
 * @param {string} [report.generated_at] - 產生時間
 * @returns {void}
 */
function exportAsText(report) {
  const { LungCancerUI } = window;

  const separator = '='.repeat(60);
  const sectionSep = '-'.repeat(40);

  const generatedAt = report.generated_at
    ? new Date(report.generated_at).toLocaleString('zh-TW')
    : new Date().toLocaleString('zh-TW');

  const content = [
    separator,
    'LUNG CANCER ANALYSIS REPORT',
    `Generated: ${generatedAt}`,
    separator,
    '',
    'FINDINGS:',
    sectionSep,
    report.findings || '（無內容）',
    '',
    'IMPRESSION:',
    sectionSep,
    report.impression || '（無內容）',
    '',
    'RECOMMENDATION:',
    sectionSep,
    report.recommendation || '（無內容）',
    '',
    separator,
    'This report is generated by Lung Cancer Analysis System.',
    'For clinical use only. Please consult a qualified physician.',
    separator,
  ].join('\n');

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const filename = generateFilename('lung_cancer_report', 'txt');
  triggerDownload(blob, filename);

  if (LungCancerUI) {
    LungCancerUI.showSuccessToast('文字報告已開始下載');
  }
}

/**
 * 下載 Heatmap 影像
 * @param {string} imageId - 影像 ID
 * @returns {Promise<void>}
 */
async function downloadHeatmapImage(imageId) {
  const { LungCancerAPI, LungCancerUI } = window;

  if (!LungCancerAPI) {
    throw new Error('API 模組未載入');
  }

  try {
    const blobUrl = await LungCancerAPI.downloadHeatmap(imageId);
    const anchor = document.createElement('a');
    anchor.href = blobUrl;
    anchor.download = generateFilename('gradcam_heatmap', 'png');
    anchor.style.display = 'none';

    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);

    setTimeout(() => URL.revokeObjectURL(blobUrl), 1000);

    if (LungCancerUI) {
      LungCancerUI.showSuccessToast('Heatmap 影像已開始下載');
    }
  } catch (error) {
    if (LungCancerUI) {
      LungCancerUI.showErrorToast(
        'Heatmap 下載失敗',
        error.detail || error.message
      );
    }
    throw error;
  }
}

// 匯出
window.LungCancerExport = {
  exportAsPDF,
  exportAsText,
  downloadHeatmapImage,
};
